### ISSUE TITLE
Leaflet 1.0 support

### ISSUE THREAD

**Issue by dmolineus** [netzmacht/php-leaflet#1]
Leaflet 1.0 has some changes which have to be implemented:
### Vectors API changes
- [x] Support of `Renderer`
- [x] Removal of `MultiPolyline` and `MultiPolygon`
- [x] `getCenter` Method of `Polyline` and `Polygon`
- [x] Changed `Circle` to inherit from `CircleMarker` and not the other way.
- [x] Removed `Polyline` and `Polygon` `spliceLatLngs`
- [x] Changed `Polygon` `getLatLngs` to always return an array of rings (nested array)
- [x] Added the ability to specify a custom pane for vector layer
- [x] Added vector layers `fillRule` option. [#2834](https://github.com/Leaflet/Leaflet/pull/2834)
- [x] Removed `L_PREFER_CANVAS` global switch and added `Map` `preferCanvas` option instead.
### Layers API improvements
- [x] Added `Layer` class which all layers added to a map should inherit from.
- [x] Added `remove` method to layers and controls (`marker.remove()` is now equivalent to `map.removeLayer(marker)`).
- [x] Added `pane` option to all layers that can be changed (e.g. you can set `pane: 'overlayPane'` to a tile layer).
- [x] Added `map` `createPane` method for custom panes. [#1742](https://github.com/Leaflet/Leaflet/issues/1742)
- [x] Added `shadowPane` option to markers as well.
- [x] Added `togglePopup`, `setPopupContent`, `getPopup`, `isPopupOpen` methods to all layers. [#2279](https://github.com/Leaflet/Leaflet/issues/2279) [#2292](https://github.com/Leaflet/Leaflet/issues/2292)
- [x] Removed `Map` `tilelayersload` event.
- [x] Renamed `clickable` option to `interactive`. [#2838](https://github.com/Leaflet/Leaflet/pull/2838) [#2499](https://github.com/Leaflet/Leaflet/issues/2499)
- [x] Added `nonBubblingEvents` option to layers [#3605](https://github.com/Leaflet/Leaflet/pull/3605) [#3307](https://github.com/Leaflet/Leaflet/pull/3307) [#3604](https://github.com/Leaflet/Leaflet/issues/3604)
### Other API improvements
- [x] Added `LatLng` `equals` second argument `maxMargin`.
- [x] Added optional support for center-oriented scroll for `L.map` option `touchZoom`. [#2527](https://github.com/Leaflet/Leaflet/pull/2527)
- [x] Added `Marker` `mousemove` event. [#2798](https://github.com/Leaflet/Leaflet/pull/2798)
- [x] Added `LatLng` `clone` method. [#3390](https://github.com/Leaflet/Leaflet/pull/3390)
- [x] Added `Map` `setMinZoom` and `setMaxZoom` method. [#3383](https://github.com/Leaflet/Leaflet/pull/3383) [#3380](https://github.com/Leaflet/Leaflet/issues/3380)
- [x] Added `Popup` `autoClose` option [#2716](https://github.com/Leaflet/Leaflet/issues/2716) [#1853](https://github.com/Leaflet/Leaflet/issues/1853)
- [x] Added `Control.Zoom` `enable` and `disable` methods. [#3172](https://github.com/Leaflet/Leaflet/issues/3172)
- [x] Added `Map` `wheelDebounceTime` option (by [@AndriiHeonia](https://github.com/AndriiHeonia)). [#2836](https://github.com/Leaflet/Leaflet/pull/2836) [#2501](https://github.com/Leaflet/Leaflet/issues/2501)
- [x] Added `ImageOverlay` `alt` option. [#2767](https://github.com/Leaflet/Leaflet/pull/2767) [#2564](https://github.com/Leaflet/Leaflet/issues/2564)
- [x] Added `Map` `maxBoundsViscosity` option that controls how much the map resits dragging out of max bounds (set to `1` for a hard limit). [#2224](https://github.com/Leaflet/Leaflet/pull/2224) [#3510](https://github.com/Leaflet/Leaflet/pull/3510) [#1673](https://github.com/Leaflet/Leaflet/issues/1673)
- [x] Added `Bounds` and `LatLngBounds` `overlaps` method. [#2981](https://github.com/Leaflet/Leaflet/issues/2981) [#3508](https://github.com/Leaflet/Leaflet/pull/3508)

**Comment by catbadger** [comment]
When updating plugins, what do I replace splicelatlngs with?

**Comment by dmolineus** [comment]
@catbadger Depends on what you want to do. LeafletPHP didn't support it anyway. If you want to convert the latlangs on PHP side, you could use https://github.com/netzmacht/php-leaflet/blob/master/src/Netzmacht/LeafletPHP/Value/LatLng.php#L125
